fix possible error where Asynchandler.event is not defined yet
If there is an error during startup, event won't be defined and the following
error will be produced:

    AttributeError: 'AsyncHandler' does not have a signal with the signature event(double)

Signed-off-by: Joshua Henderson <joshua.henderson@microchip.com>